% Produced by CVXGEN, 2016-12-28 05:27:42 -0500.
% CVXGEN is Copyright (C) 2006-2012 Jacob Mattingley, jem@cvxgen.com.
% The code in this file is Copyright (C) 2006-2012 Jacob Mattingley.
% CVXGEN, or solvers produced by CVXGEN, cannot be used for commercial
% applications without prior written permission from Jacob Mattingley.

% Filename: cvxsolve.m.
% Description: Solution file, via cvx, for use with sample.m.
function [vars, status] = cvxsolve(params, settings)
b = params.b;
in_Real_log_gz = params.in_Real_log_gz;
in_abs_Vg = params.in_abs_Vg;
k = params.k;
log_SIGMA = params.log_SIGMA;
m = params.m;
cvx_begin
  % Caution: automatically generated by cvxgen. May be incorrect.
  variable out_Real_log_gz;
  variable out_abs_Vg;

  minimize(square(in_Real_log_gz - out_Real_log_gz) + square(in_abs_Vg - out_abs_Vg));
  subject to
    out_abs_Vg >= 0;
    out_abs_Vg <= k;
    out_abs_Vg <= log_SIGMA - out_Real_log_gz;
    out_Real_log_gz >= m*out_abs_Vg + b;
cvx_end
vars.out_Real_log_gz = out_Real_log_gz;
vars.out_abs_Vg = out_abs_Vg;
status.cvx_status = cvx_status;
% Provide a drop-in replacement for csolve.
status.optval = cvx_optval;
status.converged = strcmp(cvx_status, 'Solved');
